# Generated by Django 4.2.11 on 2024-12-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartanonymousitem',
            options={'ordering': ('time_create',)},
        ),
    ]
