runtime: python
env: flex

service: default

handlers:
- url: /static
  static_dir: backend/staticfiles

runtime_config:
  python_version: 3.11

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

env_variables:
  DJANGO_SETTINGS_MODULE: "team_challenge.settings"
