runtime: python
env: flex

service: app

handlers:
- url: /static
  static_dir: backend/staticfiles

runtime_config:
  python_version: 3.12

manual_scaling:
  instances: 1

automatic_scaling:
  min_instances: 1
  max_instances: 5

env_variables:
  DJANGO_SETTINGS_MODULE: "team_challenge.settings"