version: "3"

services:
  django:
    container_name: "django"
    build: .
    command: gunicorn team_challenge.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./team_challenge:/backend/team_challenge
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my_network

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A team_challenge.celery_app.app flower
    volumes:
      - ./team_challenge:/backend/team_challenge
    environment:
      - REDIS_HOST=redis
    depends_on:
      - django
      - redis
    ports:
      - "5555:5555"
    networks:
      - my_network

  worker:
    build:
      context: .
    container_name: "worker_1"
    hostname: worker
    entrypoint: celery
    command: -A team_challenge.celery_app.app worker --loglevel=info
    volumes:
      - ./team_challenge:/team_challenge
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
    networks:
      - my_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - my_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=owner
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    networks:
      - my_network

networks:
  my_network:
    external: true