version: '3'
services:
  django:
    build: .
    command: gunicorn team_challenge.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./team_challenge:/backend/team_challenge
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=owner
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus

volumes:
  postgres_data:  
