global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
          - node-exporter:9100
          - pushgateway:9091
          - cadvisor:8081

  - job_name: django
    static_configs:
      - targets:
          - django:8000  # Assuming your Django application exposes metrics on port 8000
