version: "3.9"

services:
  django:
    container_name: "django"
    build:
      context: ..
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db && 
             gunicorn core.config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ..:/backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env

  flower:
    build:
      context: ..
    hostname: flower
    entrypoint: celery
    command: -A core.config.celery_app.app flower
    volumes:
      - ..:/backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - django
      - redis
    ports:
      - "5555:5555"

  worker:
    build:
      context: ..
    container_name: "worker_1"
    hostname: worker
    entrypoint: celery
    command: -A core.config.celery_app.app worker --loglevel=info
    volumes:
      - ..:/backend
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=owner
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
