apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        resources:
          requests:
            memory: "{{ .Values.frontend.resources.requests.memory }}"
            cpu: "{{ .Values.frontend.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.frontend.resources.limits.memory }}"
            cpu: "{{ .Values.frontend.resources.limits.cpu }}"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: frontend