apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image }}"
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.env.POSTGRES_DB }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgres.env.POSTGRES_USER }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgres.env.POSTGRES_PASSWORD }}"
        ports:
        - containerPort: {{ .Values.postgres.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
  selector:
    app: postgres