# Generated by Django 4.2.10 on 2024-02-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description_category_image_and_more'),
        ('products', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
            preserve_default=False,
        ),
    ]
