# Generated by Django 4.2.10 on 2024-03-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
