# Generated by Django 4.2.10 on 2024-03-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_color'),
        ('products', '0008_product_color'),
    ]

    operations = [
    ]
