# Generated by Django 4.2.11 on 2024-06-26 19:47

import core.apps.orders.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Simferopol', 1), ('Vinnytsia', 2), ('Lutsk', 3), ('Dnipro', 4), ('Donetsk', 5), ('Zhytomyr', 6), ('Uzhhorod', 7), ('Zaporizhzhia', 8), ('Ivano-Frankivsk', 9), ('Kyiv', 10), ('Kropyvnytskyi', 11), ('Luhansk', 12), ('Lviv', 13), ('Mykolaiv', 14), ('Odesa', 15), ('Poltava', 16), ('Rivne', 17), ('Sumy', 18), ('Ternopil', 19), ('Kharkiv', 20), ('Kherson', 21), ('Khmelnytskyi', 22), ('Cherkasy', 23), ('Chernivtsi', 24), ('Chernihiv', 25), ('Sevastopol', 26)], default='Kyiv', max_length=15)),
                ('address', models.JSONField(blank=True, default=core.apps.orders.models.Address.address_promt, max_length=64, null=True)),
                ('np_department', models.CharField(blank=True, max_length=64, null=True)),
                ('up_department', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('delivery_method', models.CharField(choices=[('Nova_Poshta', 1), ('Ukr_Poshta', 2), ('Courier', 3)], default='Ukr_Poshta', max_length=11)),
                ('payment_method', models.CharField(choices=[('card_online', 1), ('Google_Pay', 2), ('Apple_Pay', 3), ('upon_receipt', 4)], default='upon_receipt', max_length=12)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN', 'In_the_works'), ('SN', 'Sent'), ('RC', 'Received'), ('CL', 'Closed')], default='IN', max_length=2)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(through='orders.UserAddress', to='orders.address'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.user'),
        ),
    ]
