# Generated by Django 4.2 on 2024-02-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartanonymous',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cartanonymous',
            name='session',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
