# Generated by Django 4.2 on 2024-02-24 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('basket', '0002_remove_cartanonymous_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartanonymousitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartanonymousitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CartAnonymous',
        ),
        migrations.DeleteModel(
            name='CartAnonymousItem',
        ),
    ]
