# Generated by Django 4.2 on 2024-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodfuct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=255)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
