# Generated by Django 4.2 on 2024-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_prodfuct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodfuct',
        ),
    ]
