# Generated by Django 4.2 on 2024-02-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('basket', '0008_alter_cart_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAnonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartAnonymousItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.cartanonymous')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.product')),
            ],
        ),
        migrations.AddField(
            model_name='cartanonymous',
            name='products',
            field=models.ManyToManyField(through='basket.CartAnonymousItem', to='basket.product'),
        ),
        migrations.AddField(
            model_name='cartanonymous',
            name='session',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
