# Generated by Django 4.2 on 2024-02-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_produfct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produfct',
        ),
    ]
