# Generated by Django 4.2 on 2024-02-25 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_cartanonymous_remove_cart_session_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartanonymous',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartanonymous',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartanonymousitem',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartanonymousitem',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
