# Generated by Django 4.2.11 on 2024-06-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_date_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Колір'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображення продукту в каталозі'),
        ),
    ]
