# Generated by Django 4.2.11 on 2024-07-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='products.comment'),
            preserve_default=False,
        ),
    ]
