apiVersion: v2
name: team-challenge-store
description: A Helm chart for deploying the team-challenge-store and PostgreSQL
version: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 15.5.21
    repository: https://charts.bitnami.com/bitnami

