replicaCount: 2

image:
  repository: oleksandrtsybulskyy/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  image: postgres:14
  service:
    name: postgres-service
    port: 5432
  env:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mazda626

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500"

frontend:
  replicaCount: 2
  image:
    repository: oleksandrtsybulskyy/parasha
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

backend:
  env:
    SECRET_KEY: 
    DEBUG: "False"
    DB_NAME: "postgres"
    DB_USER: "postgres"