replicaCount: 2

image:
  repository: oleksandrtsybulskyy/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


postgresql:
  auth:
    postgresPassword: mazda626
    database:  postgres
    username: postgres
  primary:
    persistence:
      enabled: true
      size: 10Gi
  service:
    port: 5432

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500"

frontend:
  replicaCount: 2
  image:
    repository: oleksandrtsybulskyy/parasha
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

backend:
  env:
    SECRET_KEY: "django-insecure-g%fp$#p^xx8cdkf^4=)qxt=k-gjda+ysq)izxcb(7o=1ei%_cm"
    DEBUG: "False"
    DB_NAME: "postgres"
    DB_USER: "postgres"