# Generated by Django 4.2.11 on 2024-03-25 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('ship_method', models.CharField(choices=[('NP', 'Nova Poshta'), ('UP', 'Ukr Poshta'), ('CR', 'Courier')], default='UP', max_length=2)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN', 'In the works'), ('SN', 'Sent'), ('RC', 'Received'), ('CL', 'Closed')], default='IN', max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
