# Generated by Django 4.2.11 on 2024-05-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Simferopol', 1), ('Vinnytsia', 2), ('Lutsk', 3), ('Dnipro', 4), ('Donetsk', 5), ('Zhytomyr', 6), ('Uzhhorod', 7), ('Zaporizhzhia', 8), ('Ivano-Frankivsk', 9), ('Kyiv', 10), ('Kropyvnytskyi', 11), ('Luhansk', 12), ('Lviv', 13), ('Mykolaiv', 14), ('Odesa', 15), ('Poltava', 16), ('Rivne', 17), ('Sumy', 18), ('Ternopil', 19), ('Kharkiv', 20), ('Khmelnytskyi', 21), ('Cherkasy', 22), ('Chernivtsі', 23), ('Chernihiv', 24), ('Sevastopol', 25)], default='Kyiv', max_length=15)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('np_department', models.CharField(blank=True, max_length=64, null=True)),
                ('up_department', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_method',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Nova Poshta', 1), ('Ukr Poshta', 2), ('Courier', 3)], default='Ukr Poshta', max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card online', 1), ('Google Pay', 2), ('Apple Pay', 3), ('upon receipt', 4)], default='upon receipt', max_length=12),
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(through='orders.UserAddress', to='orders.address'),
        ),
    ]
