# Generated by Django 4.2.11 on 2024-05-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address_order_payment_method_alter_order_ship_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ship_method',
            new_name='delivery_method',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.address'),
        ),
    ]
