# Generated by Django 4.2.11 on 2024-05-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_ship_method_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Simferopol', 1), ('Vinnytsia', 2), ('Lutsk', 3), ('Dnipro', 4), ('Donetsk', 5), ('Zhytomyr', 6), ('Uzhhorod', 7), ('Zaporizhzhia', 8), ('Ivano-Frankivsk', 9), ('Kyiv', 10), ('Kropyvnytskyi', 11), ('Luhansk', 12), ('Lviv', 13), ('Mykolaiv', 14), ('Odesa', 15), ('Poltava', 16), ('Rivne', 17), ('Sumy', 18), ('Ternopil', 19), ('Kharkiv', 20), ('Kherson', 21), ('Khmelnytskyi', 22), ('Cherkasy', 23), ('Chernivtsi', 24), ('Chernihiv', 25), ('Sevastopol', 26)], default='Kyiv', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Nova_Poshta', 1), ('Ukr_Poshta', 2), ('Courier', 3)], default='Ukr Poshta', max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_online', 1), ('Google_Pay', 2), ('Apple_Pay', 3), ('upon_receipt', 4)], default='upon receipt', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN', 'In_the_works'), ('SN', 'Sent'), ('RC', 'Received'), ('CL', 'Closed')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='orders.user'),
            preserve_default=False,
        ),
    ]
