# Generated by Django 4.2.11 on 2024-05-12 12:52

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_address_city_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.JSONField(blank=True, default=orders.models.Address.address_promt, max_length=64, null=True),
        ),
    ]
