# Generated by Django 4.2 on 2024-02-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
    ]
