# Generated by Django 4.2.11 on 2024-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_confirmation_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_confirmation',
        ),
    ]
