name: Deploy Infrastructure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_KEY }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          
      - name: generate key
        run: ssh-keygen -t rsa -b 4096 -f key
        working-directory: terraform 

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform 

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: terraform 

      - name: Upload SSH key and dynamic inventory
        id: upload-files
        run: |
          echo "::set-output name=private_key::$(cat terraform/key)"
          echo "::set-output name=inventory::$(cat terraform/dynamic-inventory.ini)"

      - name: Add SSH key and inventory to GitHub secrets
        uses: peaceiris/actions-gh-secrets@v1
        with:
          secrets: |
            VM_SSH_KEY=${{ steps.upload-files.outputs.private_key }}
            DYNAMIC_INVENTORY=${{ steps.upload-files.outputs.inventory }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > terraform/key
          chmod 400 key
          ansible-playbook -i ${{ secrets.DYNAMIC_INVENTORY }} serverdp.yml

