name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: TEST REpo
        run: ls -la

      - name: Initialize Terraform
        run: terraform/terraform init

      - name: Apply Terraform configuration
        run: terraform/terraform apply -auto-approve

      - name: Upload SSH key and dynamic inventory
        run: |
          echo "::set-output name=private_key::$(cat terraform/key)"
          echo "::set-output name=inventory::$(cat terraform/dynamic-inventory.ini)"
        id: upload-files

      - name: Add SSH key to GitHub secrets
        run: |
          gh secret set VM_SSH_KEY -b"${{ steps.upload-files.outputs.private_key }}"
          gh secret set DYNAMIC_INVENTORY -b"${{ steps.upload-files.outputs.inventory }}"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > terraform/key
          chmod 400 private_key.pem
          ansible-playbook -i ${{ secrets.DYNAMIC_INVENTORY }} serverdp.yml

