name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook serverdp.yml --vault-password-file .vault_pass

      - name: Notify GitHub of the deployment
        run: gh api repos/{owner}/{repo}/deployments -f ref=main -f environment=production -f description="Deploying with GitHub Actions"
